"""
Prepaid Expense Ledger
======================
Persistent tracker for multi-period invoices that need monthly amortization.

Workflow each close:
  1. load(path)          — read existing ledger (or start fresh)
  2. merge_nexus(records, period) — add new prepaids, skip already-tracked
  3. get_current_amortization(period) — JE lines for THIS month's expense
  4. advance_period(period) — increment months_amortized, mark completed items
  5. save(wb, path)      — write updated ledger to Excel for next month's upload

The ledger is a single Excel file with two sheets:
  'Active'    — items still being amortized (uploaded each month)
  'Completed' — items fully amortized (audit trail, never removed)
"""

import re
from calendar import monthrange
from datetime import date, datetime
from dateutil.relativedelta import relativedelta
from typing import List, Dict, Any, Optional, Tuple
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


# ── Accounts that must NOT appear in the prepaid ledger ──────
#
# Prepaid Insurance (135110) and Prepaid Real Estate Taxes (135120) are
# tracked on dedicated analysis tabs in the workpaper — not in this ledger.
# Their monthly amortization JEs are generated by detect_insurance_amortization()
# and detect_retax_amortization() in accrual_entry_generator.py, which credit
# the correct offset accounts (135110 and 135120 respectively).
#
# If these expense accounts appeared in the ledger they would produce wrong JEs
# (CR 135150 Prepaid Other instead of CR 135110 / 135120) and would double-count
# the expense.  Items with these GL account numbers are excluded on load and
# blocked from entering via merge_nexus().
#
# Only items that offset against 135150 Prepaid Other belong here.
_LEDGER_EXCLUDED_GL_ACCOUNTS = {
    '639110',  # Insurance - Property        → handled by detect_insurance_amortization()
    '639120',  # Insurance - General Liability→ handled by detect_insurance_amortization()
    '641110',  # Real Estate Taxes            → handled by detect_retax_amortization()
}


# ── Schema ───────────────────────────────────────────────────

ACTIVE_COLS = [
    'vendor', 'invoice_number', 'invoice_date', 'description',
    'gl_account_number', 'gl_account', 'total_amount', 'monthly_amount',
    'service_start', 'service_end', 'total_months',
    'months_amortized', 'remaining_months', 'first_added_period',
    'daily_rate',
]

COMPLETED_COLS = ACTIVE_COLS + ['completed_period']

DARK_BLUE  = '1F4E78'
LIGHT_BLUE = 'D6E4F0'
AMBER      = 'FFF2CC'
GREEN      = 'E2EFDA'
LIGHT_GRAY = 'F2F2F2'
WHITE      = 'FFFFFF'

THIN = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'), bottom=Side(style='thin'),
)
DOUBLE_BOTTOM = Border(bottom=Side(style='double'))


def _hdr_font():
    return Font(name='Calibri', size=11, bold=True, color='FFFFFF')

def _hdr_fill():
    return PatternFill(start_color=DARK_BLUE, end_color=DARK_BLUE, fill_type='solid')

def _apply(cell, font=None, fill=None, fmt=None, border=None, align=None):
    if font:   cell.font = font
    if fill:   cell.fill = fill
    if fmt:    cell.number_format = fmt
    if border: cell.border = border
    if align:  cell.alignment = align


# ── Period helpers ───────────────────────────────────────────

_MONTH_MAP = dict(Jan=1, Feb=2, Mar=3, Apr=4, May=5, Jun=6,
                  Jul=7, Aug=8, Sep=9, Oct=10, Nov=11, Dec=12)


def _period_to_date(period_str: str) -> Optional[date]:
    """Convert 'Mar-2026' → date(2026, 3, 1). Returns None on failure."""
    if not period_str:
        return None
    m = re.search(r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[- ]?(\d{4})',
                  period_str, re.IGNORECASE)
    if m:
        mon = _MONTH_MAP.get(m.group(1).capitalize(), 0)
        yr  = int(m.group(2))
        if mon:
            return date(yr, mon, 1)
    return None


def _date_to_period(d: date) -> str:
    """Convert date(2026, 3, 1) → 'Mar-2026'."""
    return d.strftime('%b-%Y')


def _ensure_date(val) -> Optional[date]:
    """Coerce Excel cell value to date."""
    if val is None:
        return None
    if isinstance(val, date) and not isinstance(val, datetime):
        return val
    if isinstance(val, datetime):
        return val.date()
    if isinstance(val, str):
        for fmt in ('%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y'):
            try:
                return datetime.strptime(val, fmt).date()
            except ValueError:
                pass
    return None


def _invoice_key(vendor: str, invoice_number: str) -> str:
    return f"{str(vendor).strip().lower()}||{str(invoice_number).strip().lower()}"


# ── Day-based proration helpers ──────────────────────────────

def _is_partial_period(service_start: date, service_end: date) -> bool:
    """True if either the start or end date is mid-month."""
    if service_start is None or service_end is None:
        return False
    _, last_day_start = monthrange(service_start.year, service_start.month)
    _, last_day_end   = monthrange(service_end.year,   service_end.month)
    return service_start.day > 1 or service_end.day != last_day_end


def _calc_daily_rate(total_amount: float, service_start: date, service_end: date) -> float:
    """
    Daily rate for a mid-month service period.

    Convention (matches standard CRE practice — inclusive of start/end day):
      First month: days = days_in_month − start_day + 1
        e.g. Oct 20 → 31 − 20 + 1 = 12 days
      Last month:  days = end_day
        e.g. Oct 19 → 19 days
      Middle months: full calendar days in that month

    Total service days computed the same way:
      sum of (days in each calendar month spanned by the period)
      using the same partial-month convention above.
    """
    if service_start is None or service_end is None or total_amount == 0:
        return 0.0
    total_days = _count_service_days(service_start, service_end)
    return round(total_amount / total_days, 6) if total_days > 0 else 0.0


def _count_service_days(service_start: date, service_end: date) -> int:
    """
    Count total service days using inclusive partial-month convention:
      first month: days_in_month − start_day + 1  (inclusive of start day)
        e.g. Oct 20 → 31 − 20 + 1 = 12 days
      last month:  end_day  (inclusive of end day)
        e.g. Oct 19 → 19 days
      middle months: full days_in_month

    Matches the standard-mode convention in _month_amount() — both count
    the start day as a day of service.
    """
    if service_start is None or service_end is None:
        return 0
    total = 0
    cur = date(service_start.year, service_start.month, 1)
    end_month = date(service_end.year, service_end.month, 1)
    while cur <= end_month:
        _, days_in_month = monthrange(cur.year, cur.month)
        if cur.year == service_start.year and cur.month == service_start.month:
            # First month — inclusive of start day
            total += days_in_month - service_start.day + 1
        elif cur.year == service_end.year and cur.month == service_end.month:
            # Last month — inclusive of end day
            total += service_end.day
        else:
            total += days_in_month
        cur = (cur + relativedelta(months=1))
    return total


def _month_amount(item: dict, amort_date: date) -> float:
    """
    Return the correct amortization amount for a given calendar month.

    Standard mode (daily_rate == 0):
      All months use monthly_amount EXCEPT the first and last service months
      when the service period starts or ends mid-month.  Those are prorated
      as a fraction of monthly_amount (inclusive of start/end day):
        first month: monthly_amount × (days_in_month − start_day + 1) / days_in_month
          e.g. Oct 20 → 12/31 of monthly_amount
        last month:  monthly_amount × end_day / days_in_month
        middle months: monthly_amount (full)

    Day-rate mode (daily_rate > 0, legacy):
      Each month = daily_rate × days in that calendar month, inclusive of start/end day.
      Same convention as standard mode and _count_service_days().
    """
    monthly_amount = float(item.get('monthly_amount', 0) or 0)
    daily_rate     = float(item.get('daily_rate') or 0)
    service_start  = _ensure_date(item.get('service_start'))
    service_end    = _ensure_date(item.get('service_end'))
    _, days_in_month = monthrange(amort_date.year, amort_date.month)

    if daily_rate > 0:
        # Legacy day-rate mode — kept for backward compatibility.
        # Inclusive convention: start day and end day both count as service days.
        if service_start and amort_date.year == service_start.year \
                and amort_date.month == service_start.month:
            days = days_in_month - service_start.day + 1
        elif service_end and amort_date.year == service_end.year \
                and amort_date.month == service_end.month:
            days = service_end.day
        else:
            days = days_in_month
        return round(daily_rate * days, 2)

    # Standard monthly mode — prorate first and last months if mid-month
    # First month of service (starts after day 1)
    if service_start and amort_date.year == service_start.year \
            and amort_date.month == service_start.month \
            and service_start.day > 1:
        days_active = days_in_month - (service_start.day - 1)
        return round(monthly_amount * days_active / days_in_month, 2)

    # Last month of service (ends before last day of month)
    if service_end and amort_date.year == service_end.year \
            and amort_date.month == service_end.month \
            and service_end.day < days_in_month:
        return round(monthly_amount * service_end.day / days_in_month, 2)

    return monthly_amount


# ── Load ─────────────────────────────────────────────────────

def load(path: Optional[str]) -> Tuple[List[Dict], List[Dict]]:
    """
    Load existing ledger from Excel file.

    Returns (active_items, completed_items).
    If path is None or file doesn't exist, returns ([], []).
    """
    if not path:
        return [], []
    try:
        wb = load_workbook(path, data_only=True)
    except Exception:
        return [], []

    active    = _read_sheet(wb, 'Active',    ACTIVE_COLS)
    completed = _read_sheet(wb, 'Completed', COMPLETED_COLS)

    # Strip insurance and RE tax items — these belong on workpaper analysis tabs,
    # not the prepaid ledger.  Their amortization JEs come from dedicated functions
    # (detect_insurance_amortization / detect_retax_amortization) which use the
    # correct offset accounts (135110 / 135120 respectively, not 135150).
    active    = [r for r in active
                 if str(r.get('gl_account_number', '') or '').strip()
                 not in _LEDGER_EXCLUDED_GL_ACCOUNTS]
    completed = [r for r in completed
                 if str(r.get('gl_account_number', '') or '').strip()
                 not in _LEDGER_EXCLUDED_GL_ACCOUNTS]

    return active, completed


_DISPLAY_TO_INTERNAL = {
    'vendor':               'vendor',
    'invoice #':            'invoice_number',
    'invoice date':         'invoice_date',
    'description':          'description',
    'gl account #':         'gl_account_number',
    'gl account name':      'gl_account',
    'total amount':         'total_amount',
    'monthly amt':          'monthly_amount',
    'service start':        'service_start',
    'service end':          'service_end',
    'total months':         'total_months',
    'months posted':        'months_amortized',
    'months left':          'remaining_months',
    'first added':          'first_added_period',
    'daily rate':           'daily_rate',
    'completed period':     'completed_period',
}


def _read_sheet(wb: Workbook, sheet_name: str, expected_cols: List[str]) -> List[Dict]:
    if sheet_name not in wb.sheetnames:
        return []
    ws = wb[sheet_name]
    rows = list(ws.values)
    if len(rows) < 2:
        return []

    # Find header row (first row containing 'Vendor' or 'vendor')
    header_row_idx = None
    raw_headers = []
    for i, row in enumerate(rows):
        row_strs = [str(c).strip().lower() if c else '' for c in row]
        if 'vendor' in row_strs:
            header_row_idx = i
            raw_headers = [str(c).strip().lower() if c else '' for c in row]
            break

    if header_row_idx is None:
        return []

    # Map display header names → internal field names
    mapped_headers = [_DISPLAY_TO_INTERNAL.get(h, h) for h in raw_headers]

    records = []
    for row in rows[header_row_idx + 1:]:
        if all(c is None or str(c).strip() == '' for c in row):
            continue
        # Skip totals / summary rows (no vendor value)
        vendor_idx = mapped_headers.index('vendor') if 'vendor' in mapped_headers else 0
        if vendor_idx < len(row) and (row[vendor_idx] is None or str(row[vendor_idx]).strip() == ''):
            continue
        # Skip rows where vendor looks like a label (e.g. 'TOTAL')
        vendor_val = str(row[vendor_idx]).strip() if vendor_idx < len(row) else ''
        if vendor_val.upper() in ('TOTAL', 'GRAND TOTAL', ''):
            continue

        rec = {}
        for ci, h in enumerate(mapped_headers):
            if ci < len(row):
                rec[h] = row[ci]

        # Coerce date fields
        for df in ('invoice_date', 'service_start', 'service_end'):
            rec[df] = _ensure_date(rec.get(df))

        # Coerce numeric fields
        for nf in ('total_amount', 'monthly_amount', 'total_months',
                   'months_amortized', 'remaining_months', 'daily_rate'):
            v = rec.get(nf)
            try:
                rec[nf] = float(v) if v is not None and str(v).strip() != '' else 0.0
            except (TypeError, ValueError):
                rec[nf] = 0.0

        records.append(rec)

    return records


# ── Merge new Nexus prepaids ─────────────────────────────────

def merge_nexus(active: List[Dict], nexus_records: List[Dict],
                close_period: str) -> Tuple[List[Dict], List[str]]:
    """
    Add new prepaid invoices from Nexus that aren't already in the ledger.

    Args:
        active:        Existing active ledger items
        nexus_records: Parsed Nexus records (from nexus_accrual.parse())
        close_period:  Current close period string e.g. 'Mar-2026'

    Returns:
        (updated_active, list_of_new_invoice_numbers_added)
    """
    existing_keys = {_invoice_key(r.get('vendor', ''), r.get('invoice_number', ''))
                     for r in active}
    added = []

    for inv in nexus_records:
        if not inv.get('is_prepaid'):
            continue
        # Insurance and RE tax expense accounts are excluded from the ledger —
        # their amortization is handled by dedicated accrual generator functions.
        if str(inv.get('gl_account_number', '') or '').strip() in _LEDGER_EXCLUDED_GL_ACCOUNTS:
            continue
        key = _invoice_key(inv.get('vendor', ''), inv.get('invoice_number', ''))
        if key in existing_keys:
            continue

        total_months = inv.get('prepaid_months', 1)
        total_amount = inv.get('amount', 0)
        monthly_amount = round(total_amount / total_months, 2)

        svc_start = _ensure_date(inv.get('service_start'))
        svc_end   = _ensure_date(inv.get('service_end'))

        # Day-based proration: auto-detect mid-month start or end.
        # Sets daily_rate so get_current_amortization() can compute the exact
        # calendar-day amount for each month (partial first, full middle, partial last).
        if svc_start and svc_end and _is_partial_period(svc_start, svc_end):
            daily_rate = _calc_daily_rate(total_amount, svc_start, svc_end)
            # Anchor = service_start month (e.g. Oct for an Oct 20 start).
            # months_amortized=0 → get_current_amortization() skips month 0
            # (the partial first month is handled by the Nexus accrual JE).
            # months_amortized=1 → amort_month = Oct+1 = Nov (first full month) ✓
            # months_amortized=N → amort_month = Oct+N, using daily_rate for
            # partial last month and full days for all middle months.
            first_added = _date_to_period(date(svc_start.year, svc_start.month, 1))
        else:
            daily_rate   = 0.0
            first_added  = close_period

        # For partial-period items the anchor month (service_start month) is
        # slot 0 and is skipped by get_current_amortization() — but advance_period()
        # still increments months_amortized, consuming one slot.  To ensure all
        # total_months JEs fire we start remaining_months at total_months + 1 so
        # the skip slot doesn't eat one of the real release periods.
        init_remaining = float(total_months + 1) if daily_rate > 0 else float(total_months)

        active.append({
            'vendor':            inv.get('vendor', ''),
            'invoice_number':    inv.get('invoice_number', ''),
            'invoice_date':      inv.get('invoice_date'),
            'description':       inv.get('line_description', ''),
            'gl_account_number': inv.get('gl_account_number', ''),
            'gl_account':        inv.get('gl_account', ''),
            'total_amount':      total_amount,
            'monthly_amount':    monthly_amount,
            'service_start':     svc_start,
            'service_end':       svc_end,
            'total_months':      float(total_months),
            'months_amortized':  0.0,
            'remaining_months':  init_remaining,
            'first_added_period': first_added,
            'daily_rate':        daily_rate,
        })
        existing_keys.add(key)
        added.append(inv.get('invoice_number', ''))

    return active, added


# ── Generate current period amortization JE lines ───────────

def get_current_amortization(active: List[Dict], close_period: str,
                              suppressed_invoice_numbers: Optional[set] = None) -> List[Dict]:
    """
    Return one amortization record per active ledger item for the current period.

    Each record has enough info to build a JE:
      DR  [gl_account_number]  amount_for_this_month
      CR  135150 Prepaid Other  amount_for_this_month

    Items with months_amortized == 0 added THIS period: first month is normally
      handled by the Nexus accrual JE — skipped here to avoid a duplicate.
      EXCEPTION: if the Nexus JE was suppressed (invoice already in GL and
      deduplicated by build_accrual_entries), pass the invoice number in
      ``suppressed_invoice_numbers`` so month-1 is emitted here instead.
      Without this, month-1 expense would be permanently lost — advance_period()
      still increments months_amortized, so month-2 fires next close as if
      month-1 had been handled.
    Items with months_amortized == 0 added in a PRIOR period (initial / legacy
      ledger setup): rebased to release this period by treating close_period − 1
      month as the new anchor. The item is updated in-place so advance_period
      and all future closes chain forward correctly.
    Items with months_amortized >= 1: normal release — fires when
      anchor + months_amortized == close_period.

    Args:
        active:                      Active ledger items (from load() or merge_nexus())
        close_period:                Current close period string e.g. 'Mar-2026'
        suppressed_invoice_numbers:  Optional set of invoice number strings (lowercased)
                                     whose Nexus accrual JE was NOT emitted because the
                                     expense was already in GL.  When a new item's invoice
                                     number is in this set, month-1 is emitted by the ledger
                                     rather than skipped.

    Day-based proration: if the item has daily_rate > 0 (set automatically by
    merge_nexus() when service_start is mid-month or service_end is mid-month),
    the amount for each calendar month is computed as:
      first month:  daily_rate × (days_in_month − service_start.day)
      last month:   daily_rate × service_end.day
      middle months: daily_rate × days_in_month
    This matches the convention: 11 days for Oct 20 start (31 − 20 = 11).
    """
    close_date = _period_to_date(close_period)
    if close_date is None:
        # Cannot determine which period to amortize — return nothing rather
        # than silently releasing every active item at once.
        return []

    results = []

    for item in active:
        svc_start = _ensure_date(item.get('service_start'))
        if not svc_start:
            continue

        months_done = int(item.get('months_amortized', 0) or 0)
        remaining   = int(item.get('remaining_months', 0) or 0)

        if remaining <= 0:
            continue

        # ── Determine anchor and handle first-month logic ────────────────────
        first_added = _period_to_date(item.get('first_added_period', ''))

        if months_done == 0:
            # Anchor for the zero-case: use first_added_period (may be set to a
            # prior period in seed/legacy files).
            anchor = first_added or date(svc_start.year, svc_start.month, 1)

            # Items added this period: month-1 expense is normally covered by the
            # Nexus accrual JE — skip here to avoid a duplicate.
            # EXCEPTION: when the Nexus JE was suppressed (expense was already
            # posted to GL and deduplicated by build_accrual_entries), the prepaid
            # ledger must emit month-1 itself.  The caller signals suppression by
            # including the invoice number in suppressed_invoice_numbers.
            if (close_date and anchor.year == close_date.year
                    and anchor.month == close_date.month):
                _inv_key = str(item.get('invoice_number', '') or '').strip().lower()
                _nexus_suppressed = (
                    bool(suppressed_invoice_numbers)
                    and bool(_inv_key)
                    and _inv_key in suppressed_invoice_numbers
                )
                if not _nexus_suppressed:
                    continue  # Nexus JE covers month-1; skip here to avoid duplicate

                # Nexus JE was suppressed — emit month-1 directly.
                # anchor == close_date, months_done == 0 → amort_month = close_date.
                # We do NOT rebase the anchor (no in-place mutation) so that
                # advance_period() increments months_amortized 0→1 and next month
                # uses anchor=service_start + 1 = month-2 correctly.
                _m1_amount = _month_amount(item, close_date)
                results.append({
                    'vendor':            item.get('vendor', ''),
                    'invoice_number':    item.get('invoice_number', ''),
                    'description':       item.get('description', ''),
                    'gl_account_number': item.get('gl_account_number', ''),
                    'gl_account':        item.get('gl_account', ''),
                    'monthly_amount':    _m1_amount,
                    'period_label':      _date_to_period(close_date),
                    'month_index':       1,
                    'total_months':      int(item.get('total_months', 1) or 1),
                    'source':            'prepaid_ledger',
                    'is_day_based':      float(item.get('daily_rate') or 0) > 0,
                })
                continue  # skip legacy-rebase block and amort_month check below

            # Legacy / initial-setup item: months_amortized was never incremented
            # (e.g. the prepaid ledger was created manually for the first time).
            # Rebase anchor to (close_period − 1 month) so amort_month lands on
            # close_period this run, and future months chain forward correctly.
            # Also persist the new first_added_period so advance_period and the
            # next close calculate correctly.
            if close_date:
                new_anchor = close_date - relativedelta(months=1)
                item['first_added_period'] = _date_to_period(new_anchor)
                item['months_amortized']   = 1
                # Feb+ months anchor from service_start, not first_added_period.
                # Update service_start to new_anchor so the sequence chains correctly:
                #   Jan: months_done=1, anchor=new_anchor     → amort = close_period ✓
                #   Feb: months_done=2, anchor=service_start  → amort = close_period+1 ✓
                item['service_start']      = new_anchor
                anchor      = new_anchor
                months_done = 1
            else:
                continue   # can't determine period; skip

        else:
            # For items with months already posted, always anchor from service_start.
            # first_added_period is only reliable for the months_amortized=0 rebase
            # case; seed/manual ledger files often set it to the ledger-creation date
            # rather than the true service start, which would produce wrong amort months.
            anchor = date(svc_start.year, svc_start.month, 1)

        # Verify this item is due this period.
        amort_month = anchor + relativedelta(months=months_done)
        if close_date and (amort_month.year != close_date.year or
                           amort_month.month != close_date.month):
            continue

        # Amount: day-based if daily_rate set, otherwise fixed monthly_amount
        amount = _month_amount(item, amort_month)

        results.append({
            'vendor':            item.get('vendor', ''),
            'invoice_number':    item.get('invoice_number', ''),
            'description':       item.get('description', ''),
            'gl_account_number': item.get('gl_account_number', ''),
            'gl_account':        item.get('gl_account', ''),
            'monthly_amount':    amount,
            'period_label':      _date_to_period(amort_month),
            'month_index':       months_done + 1,
            'total_months':      int(item.get('total_months', 1) or 1),
            'source':            'prepaid_ledger',
            'is_day_based':      float(item.get('daily_rate') or 0) > 0,
        })

    return results


# ── Advance period ───────────────────────────────────────────

def advance_period(active: List[Dict], completed: List[Dict],
                   close_period: str) -> Tuple[List[Dict], List[Dict]]:
    """
    After the close period JEs are posted:
      - Increment months_amortized by 1 for each active item
      - Move items with remaining_months == 0 to completed list
      - Return (new_active, new_completed)
    """
    new_active = []
    for item in active:
        item = dict(item)  # copy
        months_done = int(item.get('months_amortized', 0) or 0)
        remaining   = int(item.get('remaining_months', 0) or 0)

        item['months_amortized'] = months_done + 1
        # Decrement directly from remaining_months rather than recomputing from
        # total_months.  This preserves the +1 init for partial-period items
        # (where slot 0 is the anchor-skip month) and is also more robust for
        # manually-adjusted ledger values.
        item['remaining_months'] = max(0, remaining - 1)

        if item['remaining_months'] <= 0:
            item['completed_period'] = close_period
            completed.append(item)
        else:
            new_active.append(item)

    return new_active, completed


# ── Save to Excel ─────────────────────────────────────────────

def save(active: List[Dict], completed: List[Dict], path: str, period: str = '',
         property_name: str = '') -> str:
    """
    Write the ledger to Excel with three tabs:
      1. '135150 PPD Other' — workpaper-format schedule (matches Pass 2 workpaper layout)
      2. 'Active'           — pipeline tracking sheet (all active amortization items)
      3. 'Completed'        — audit trail of fully amortized items
    """
    wb = Workbook()

    # Workpaper-format tab first — identical layout to build_135150_tab() in Pass 2
    _write_135150_workpaper_tab(wb, active, period, property_name=property_name)

    _write_sheet(wb, 'Active', active, ACTIVE_COLS,
                 title='Prepaid Expense Ledger — Active Items',
                 tab_color='2E75B6')

    _write_sheet(wb, 'Completed', completed, COMPLETED_COLS,
                 title='Prepaid Expense Ledger — Completed Items',
                 tab_color='70AD47')

    # Remove default sheet
    if 'Sheet' in wb.sheetnames:
        del wb['Sheet']

    wb.save(path)
    return path


def _write_135150_workpaper_tab(wb: Workbook, active: List[Dict], period: str,
                                property_name: str = '') -> None:
    """
    Create a workpaper-format '135150 PPD Other' tab as the first sheet.

    Layout mirrors build_135150_tab() in account_tab_builders.py exactly:
      Row 1:  Account title (dark green header)
      Row 2:  Property | Period | Prepared
      Row 3:  (blank spacer)
      Row 4:  Column headers (black bg, white text)
      Row 5+: Data rows (alternating white/light-gray)
      Footer: Ending Balance per GL = sum(remaining_months × monthly_amount)

    Columns: Vendor | Description | Invoice Number | Invoice Date | G/L Account |
             Start Date | End Date | Total | Monthly Amt | Amt Amort. | Remaining
    """
    ws = wb.create_sheet('135150 PPD Other', 0)   # insert first
    ws.sheet_properties.tabColor = '70AD47'
    ws.column_dimensions['A'].width = 2

    HDR_GREEN     = '375623'
    COL_HDR_BLACK = '000000'
    FIRST_COL     = 2    # col B
    LAST_COL      = 12   # col L (11 data columns: B–L)

    col_labels = ['Vendor', 'Description', 'Invoice Number', 'Invoice Date',
                  'G/L Account', 'Start Date', 'End Date',
                  'Total', 'Monthly Amt', 'Amt Amort.', 'Remaining']
    col_widths = [24, 32, 16, 14, 14, 12, 12, 16, 14, 14, 16]

    for ci, w in enumerate(col_widths):
        ws.column_dimensions[get_column_letter(FIRST_COL + ci)].width = w

    # ── Rows 1-3: header block (same structure as Pass 2 workpaper) ───────
    # B1 = account code only — mirrors account_tab_builders.build_135150_tab()
    c = ws.cell(row=1, column=FIRST_COL, value='135150')
    c.font      = Font(name='Calibri', size=13, bold=True, color='FFFFFF')
    c.fill      = PatternFill(start_color=HDR_GREEN, end_color=HDR_GREEN, fill_type='solid')
    c.alignment = Alignment(horizontal='left', vertical='center')
    ws.merge_cells(start_row=1, start_column=FIRST_COL, end_row=1, end_column=FIRST_COL + 2)
    ws.row_dimensions[1].height = 20

    c = ws.cell(row=2, column=FIRST_COL, value='Prepaid - Other')
    c.font      = Font(name='Calibri', size=11, color='FFFFFF')
    c.fill      = PatternFill(start_color=HDR_GREEN, end_color=HDR_GREEN, fill_type='solid')
    c.alignment = Alignment(horizontal='left', vertical='center')
    ws.merge_cells(start_row=2, start_column=FIRST_COL, end_row=2, end_column=LAST_COL)

    prop_line = (f'{property_name or "[Property]"}  |  Period: {period}  |  '
                 f'Prepared: {datetime.now().strftime("%m/%d/%Y")}')
    c = ws.cell(row=3, column=FIRST_COL, value=prop_line)
    c.font      = Font(name='Calibri', size=10, italic=True, color='FFFFFF')
    c.fill      = PatternFill(start_color=HDR_GREEN, end_color=HDR_GREEN, fill_type='solid')
    c.alignment = Alignment(horizontal='left', vertical='center')
    ws.merge_cells(start_row=3, start_column=FIRST_COL, end_row=3, end_column=LAST_COL)

    # Row 4: blank spacer (matches workpaper layout — data starts at row 6)

    # ── Row 5: Column headers ─────────────────────────────────────────────
    for ci, lbl in enumerate(col_labels):
        col = FIRST_COL + ci
        c = ws.cell(row=5, column=col, value=lbl)
        c.font      = Font(name='Calibri', size=10, bold=True, color='FFFFFF')
        c.fill      = PatternFill(start_color=COL_HDR_BLACK, end_color=COL_HDR_BLACK, fill_type='solid')
        c.border    = THIN
        c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[5].height = 18

    # ── Data rows from row 6 ──────────────────────────────────────────────
    # Values only (no DATEDIF formulas — this file is standalone, no Summary Page).
    # Amt Amort. and Remaining are Python-computed dollar amounts.
    next_row = 6
    for i, rec in enumerate(active):
        alt = i % 2 == 1
        alt_fill = PatternFill(start_color=LIGHT_GRAY, end_color=LIGHT_GRAY,
                               fill_type='solid') if alt else None

        vendor     = str(rec.get('vendor') or rec.get('description') or '')
        desc       = str(rec.get('description') or '')
        inv_num    = str(rec.get('invoice_number') or '')
        inv_date   = rec.get('invoice_date') or ''
        gl_account = str(rec.get('gl_account_number') or '')
        start      = rec.get('service_start') or rec.get('first_added_period') or ''
        end        = rec.get('service_end') or ''
        total      = float(rec.get('total_amount') or 0)
        monthly    = float(rec.get('monthly_amount') or 0)
        months_am  = int(rec.get('months_amortized') or 0)
        rem_months = int(rec.get('remaining_months') or 0)
        amt_amort  = round(months_am * monthly, 2)
        remaining  = round(rem_months * monthly, 2)

        row_vals = [
            (vendor,                             None,        True),
            (desc,                               None,        True),
            (inv_num,                            None,        False),
            (str(inv_date) if inv_date else '',  None,        False),
            (gl_account,                         None,        False),
            (str(start),                         None,        False),
            (str(end),                           None,        False),
            (total,                              '$#,##0.00', False),
            (monthly,                            '$#,##0.00', False),
            (amt_amort,                          '$#,##0.00', False),
            (remaining,                          '$#,##0.00', False),
        ]
        for ci, (val, fmt, wrap) in enumerate(row_vals):
            col = FIRST_COL + ci
            c = ws.cell(row=next_row, column=col, value=val)
            c.font   = Font(name='Calibri', size=10)
            c.border = THIN
            if alt_fill:
                c.fill = alt_fill
            c.number_format = fmt or 'General'
            c.alignment = Alignment(
                wrap_text=wrap,
                horizontal='right' if fmt else 'left',
            )
        next_row += 1

    last_data_row = max(next_row - 1, 5)

    if not active:
        c = ws.cell(row=next_row, column=FIRST_COL, value='No active prepaid items')
        c.font = Font(name='Calibri', size=10, italic=True, color='666666')
        next_row += 1

    # ── Footer: Ending Balance per GL (live SUM formula) ──────────────────
    next_row += 1   # blank separator

    for col in range(FIRST_COL, LAST_COL + 1):
        ws.cell(row=next_row, column=col).border = Border(bottom=Side(style='medium'))
    next_row += 1

    L = get_column_letter(LAST_COL)

    c_lbl = ws.cell(row=next_row, column=FIRST_COL, value='Ending Balance per GL')
    c_lbl.font      = Font(name='Calibri', size=10, bold=True, color='FFFFFF')
    c_lbl.fill      = PatternFill(start_color=DARK_BLUE, end_color=DARK_BLUE, fill_type='solid')
    c_lbl.border    = THIN
    c_lbl.alignment = Alignment(horizontal='left')
    ws.merge_cells(start_row=next_row, start_column=FIRST_COL,
                   end_row=next_row, end_column=LAST_COL - 1)

    c_val = ws.cell(row=next_row, column=LAST_COL,
                    value=f'=SUM({L}6:{L}{last_data_row})')
    c_val.font         = Font(name='Calibri', size=10, bold=True, color='FFFFFF')
    c_val.fill         = PatternFill(start_color=DARK_BLUE, end_color=DARK_BLUE, fill_type='solid')
    c_val.border       = THIN
    c_val.number_format = '$#,##0.00'
    c_val.alignment    = Alignment(horizontal='right')


def _write_sheet(wb: Workbook, sheet_name: str, records: List[Dict],
                 cols: List[str], title: str, tab_color: str):
    ws = wb.create_sheet(sheet_name)
    ws.sheet_properties.tabColor = tab_color

    # Title
    ws.cell(row=1, column=1, value=title).font = Font(
        name='Calibri', size=13, bold=True, color=DARK_BLUE)
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(cols))

    ws.cell(row=2, column=1,
            value=f'Updated: {datetime.now().strftime("%m/%d/%Y %I:%M %p")}  |  {len(records)} item(s)').font = Font(
        name='Calibri', size=10, italic=True, color='666666')
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(cols))

    # Headers
    DISPLAY = {
        'vendor': 'Vendor', 'invoice_number': 'Invoice #',
        'invoice_date': 'Invoice Date', 'description': 'Description',
        'gl_account_number': 'GL Account #', 'gl_account': 'GL Account Name',
        'total_amount': 'Total Amount', 'monthly_amount': 'Monthly Amt',
        'service_start': 'Service Start', 'service_end': 'Service End',
        'total_months': 'Total Months', 'months_amortized': 'Months Posted',
        'remaining_months': 'Months Left', 'first_added_period': 'First Added',
        'daily_rate': 'Daily Rate',
        'completed_period': 'Completed Period',
    }
    hdr_row = 4
    for ci, col in enumerate(cols, 1):
        c = ws.cell(row=hdr_row, column=ci, value=DISPLAY.get(col, col))
        _apply(c, font=_hdr_font(), fill=_hdr_fill(), border=THIN,
               align=Alignment(horizontal='center', vertical='center', wrap_text=True))
    ws.row_dimensions[hdr_row].height = 30

    # Data
    for ri, rec in enumerate(records, hdr_row + 1):
        # Highlight active items with remaining months <= 1 (almost done)
        remaining = int(rec.get('remaining_months', 99) or 99)
        row_fill = None
        if sheet_name == 'Active':
            if remaining == 1:
                row_fill = PatternFill(start_color=AMBER, end_color=AMBER, fill_type='solid')
            elif ri % 2 == 0:
                row_fill = PatternFill(start_color=LIGHT_GRAY, end_color=LIGHT_GRAY, fill_type='solid')

        for ci, col in enumerate(cols, 1):
            val = rec.get(col, '')
            c = ws.cell(row=ri, column=ci, value=val)
            c.border = THIN
            if row_fill:
                c.fill = row_fill

            # Formatting by column type
            if col in ('total_amount', 'monthly_amount'):
                c.number_format = '$#,##0.00'
            elif col == 'daily_rate':
                c.number_format = '$#,##0.000000'
            elif col in ('invoice_date', 'service_start', 'service_end'):
                if isinstance(val, date):
                    c.number_format = 'MM/DD/YYYY'
            elif col in ('total_months', 'months_amortized', 'remaining_months'):
                c.number_format = '0'
                c.alignment = Alignment(horizontal='center')
                # Highlight items nearing completion in the Active sheet
                if col == 'remaining_months' and sheet_name == 'Active':
                    if remaining == 0:
                        c.font = Font(name='Calibri', color='FF0000', bold=True)
                    elif remaining == 1:
                        c.font = Font(name='Calibri', color='C55A11', bold=True)

    # Totals row (active sheet only)
    if sheet_name == 'Active' and records:
        total_row = hdr_row + len(records) + 1
        total_col_map = {col: i + 1 for i, col in enumerate(cols)}

        ws.cell(row=total_row,
                column=total_col_map.get('description', 1),
                value='TOTAL').font = Font(name='Calibri', size=11, bold=True)

        for fcol in ('total_amount', 'monthly_amount'):
            ci = total_col_map.get(fcol)
            if ci:
                total = sum(float(r.get(fcol, 0) or 0) for r in records)
                c = ws.cell(row=total_row, column=ci, value=total)
                c.number_format = '$#,##0.00'
                c.font = Font(name='Calibri', size=11, bold=True)
                c.border = DOUBLE_BOTTOM

    # Column widths
    col_widths = {
        'vendor': 28, 'invoice_number': 16, 'invoice_date': 13,
        'description': 38, 'gl_account_number': 14, 'gl_account': 32,
        'total_amount': 14, 'monthly_amount': 13, 'service_start': 13,
        'service_end': 13, 'total_months': 10, 'months_amortized': 12,
        'remaining_months': 12, 'first_added_period': 13, 'daily_rate': 12,
        'completed_period': 14,
    }
    for ci, col in enumerate(cols, 1):
        ws.column_dimensions[get_column_letter(ci)].width = col_widths.get(col, 14)

    ws.freeze_panes = ws.cell(row=hdr_row + 1, column=1)


# ── Seed Ledger Generator ─────────────────────────────────────────────────────

def generate_seed(
    items: List[Dict[str, Any]],
    as_of_period: str,
    output_path: Optional[str] = None,
) -> bytes:
    """
    Build a prepaid ledger seed Excel file from a list of manually-entered items.

    Intended for onboarding new or acquired properties: Ryan enters all active
    prepaid items (with their current amortization state) and downloads the seed
    file to upload as the "prior month ledger" on the first close.

    Each item dict should contain:
        vendor              (str)  — required
        description         (str)  — required
        gl_account_number   (str)  — required, 6-digit GL code (e.g. '619120')
        gl_account          (str)  — GL account name (e.g. 'PPM Water Treatment')
        total_amount        (float)— original total invoice / contract amount
        monthly_amount      (float)— amortization per month; if 0 or missing,
                                     auto-computed as total_amount ÷ total_months
        service_start       (date | str) — first day of service period
        service_end         (date | str) — last day of service period
        months_amortized    (int)  — months already released by prior management
                                     (0 = greenfield / not yet started)
        invoice_number      (str)  — optional
        invoice_date        (date | str) — optional

    Returns the Excel file as bytes (also writes to output_path when provided).

    Notes:
    - Items with gl_account_number in _LEDGER_EXCLUDED_GL_ACCOUNTS (639110, 639120,
      641110) are silently skipped — those accounts are managed by dedicated
      detect_insurance_amortization / detect_retax_amortization functions.
    - total_months is computed from service_start → service_end using relativedelta.
    - remaining_months = total_months − months_amortized (floor 0).
    - first_added_period is set to as_of_period for all items.
    - daily_rate is set to 0 (seed items use monthly amortization only).
    """
    import io

    active: List[Dict[str, Any]] = []

    for raw in items:
        code = str(raw.get('gl_account_number', '') or '').strip()
        if code in _LEDGER_EXCLUDED_GL_ACCOUNTS:
            continue   # insurance/RE-tax: handled by dedicated functions

        vendor = str(raw.get('vendor', '') or '').strip()
        if not vendor:
            continue   # skip blank rows

        s_start = _ensure_date(raw.get('service_start'))
        s_end   = _ensure_date(raw.get('service_end'))

        # Compute total_months from date range; fall back to caller-supplied value
        if s_start and s_end and s_end >= s_start:
            rd = relativedelta(s_end + relativedelta(days=1), s_start)
            total_months = rd.years * 12 + rd.months
            if total_months < 1:
                total_months = 1
        else:
            total_months = max(1, int(raw.get('total_months', 1) or 1))

        months_amortized = max(0, int(raw.get('months_amortized', 0) or 0))
        remaining_months = max(0, total_months - months_amortized)

        total_amount  = float(raw.get('total_amount', 0)  or 0)
        monthly_amount = float(raw.get('monthly_amount', 0) or 0)
        if monthly_amount <= 0 and total_months > 0:
            monthly_amount = round(total_amount / total_months, 2)

        active.append({
            'vendor':             vendor,
            'invoice_number':     str(raw.get('invoice_number', '') or ''),
            'invoice_date':       _ensure_date(raw.get('invoice_date')),
            'description':        str(raw.get('description', '') or ''),
            'gl_account_number':  code,
            'gl_account':         str(raw.get('gl_account', '') or ''),
            'total_amount':       total_amount,
            'monthly_amount':     monthly_amount,
            'service_start':      s_start,
            'service_end':        s_end,
            'total_months':       float(total_months),
            'months_amortized':   float(months_amortized),
            'remaining_months':   float(remaining_months),
            'first_added_period': as_of_period,
            'daily_rate':         0.0,
        })

    # Build the workbook using the existing save() pipeline (identical format to
    # a real ledger so prepaid_ledger.load() reads it without any special handling)
    buf_path = output_path or '__seed_tmp__.xlsx'

    # Use a BytesIO buffer when no path is specified
    if output_path:
        save(active, [], output_path, period=as_of_period)
        with open(output_path, 'rb') as fh:
            return fh.read()
    else:
        import tempfile, os
        with tempfile.NamedTemporaryFile(suffix='.xlsx', delete=False) as tmp:
            _tmp = tmp.name
        try:
            save(active, [], _tmp, period=as_of_period)
            with open(_tmp, 'rb') as fh:
                return fh.read()
        finally:
            try:
                os.unlink(_tmp)
            except Exception:
                pass
