"""
Report Generator for GA Automation Pipeline
==============================================
Takes parsed data from all parsers (via EngineResult) and produces the
exception/validation report:
  - Summary: Overview of pipeline run
  - Exceptions: All flagged issues with severity/category
  - Budget Variances: Material variances from budget
  - Bank Recon: GL to bank matching results
  - Debt Service: Loan statement reconciliation

(The Singerman 8-tab monthly report is downloaded directly from Yardi —
not generated by this module.)
"""

import os
from datetime import datetime
from typing import Optional
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


# ── Styling utilities ────────────────────────────────────────

def _header_style():
    """Create dark blue header style with white text."""
    return {
        'font': Font(name='Calibri', size=11, bold=True, color='FFFFFF'),
        'fill': PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid'),
        'alignment': Alignment(horizontal='center', vertical='center', wrap_text=True),
        'border': Border(
            left=Side(style='thin'),
            right=Side(style='thin'),
            top=Side(style='thin'),
            bottom=Side(style='thin'),
        )
    }


def _data_style(alternate: bool = False):
    """Create data row style with optional alternating color."""
    fill_color = 'D9E1F2' if alternate else 'FFFFFF'
    return {
        'font': Font(name='Calibri', size=11),
        'fill': PatternFill(start_color=fill_color, end_color=fill_color, fill_type='solid'),
        'alignment': Alignment(horizontal='left', vertical='center'),
        'border': Border(
            left=Side(style='thin'),
            right=Side(style='thin'),
            top=Side(style='thin'),
            bottom=Side(style='thin'),
        )
    }


def _currency_style(alternate: bool = False):
    """Create currency-formatted data style."""
    style = _data_style(alternate)
    style['number_format'] = '$#,##0.00'
    return style


def _percent_style(alternate: bool = False):
    """Create percentage-formatted data style."""
    style = _data_style(alternate)
    style['number_format'] = '0.0%'
    return style


def _apply_style(cell, style):
    """Apply a style dict to a cell."""
    if 'font' in style:
        cell.font = style['font']
    if 'fill' in style:
        cell.fill = style['fill']
    if 'alignment' in style:
        cell.alignment = style['alignment']
    if 'border' in style:
        cell.border = style['border']
    if 'number_format' in style:
        cell.number_format = style['number_format']


def _auto_width_columns(ws, columns: int):
    """Auto-fit column widths."""
    for col_num in range(1, columns + 1):
        col_letter = get_column_letter(col_num)
        max_len = 12
        for cell in ws[col_letter]:
            try:
                if cell.value:
                    cell_len = len(str(cell.value))
                    if cell_len > max_len:
                        max_len = cell_len
            except:
                pass
        ws.column_dimensions[col_letter].width = min(max_len + 2, 50)



# ── Exception report generator ───────────────────────────────

def generate_exception_report(engine_result, output_path: str) -> str:
    """
    Generate an exception and validation detail report.

    Args:
        engine_result: EngineResult object with exceptions and validation data
        output_path: Where to write the Excel file

    Returns:
        The output path if successful
    """
    wb = Workbook()
    wb.remove(wb.active)  # Remove default blank sheet

    # --- Tab 1: Summary ---
    _write_summary_tab(wb, engine_result)

    # --- Tab 2: Exceptions ---
    _write_exceptions_tab(wb, engine_result)

    # --- Tab 3: Budget Variances ---
    _write_budget_variances_tab(wb, engine_result)

    # --- Tab 4: Bank Recon ---
    _write_bank_recon_tab(wb, engine_result)

    # --- Tab 5: Debt Service ---
    _write_debt_service_tab(wb, engine_result)

    # Write workbook
    wb.save(output_path)
    return output_path


def _write_summary_tab(wb: Workbook, engine_result):
    """Write Summary tab with overview statistics."""
    ws = wb.create_sheet('Summary', 0)

    summary_data = engine_result.summary or {}

    # Title
    ws['A1'] = 'GA Automation Pipeline Summary'
    ws['A1'].font = Font(name='Calibri', size=14, bold=True)
    ws.merge_cells('A1:B1')

    # Run details
    row = 3
    ws[f'A{row}'] = 'Run ID:'
    ws[f'B{row}'] = engine_result.run_id
    row += 1
    ws[f'A{row}'] = 'Run At:'
    ws[f'B{row}'] = engine_result.run_at
    row += 1
    ws[f'A{row}'] = 'Period:'
    ws[f'B{row}'] = engine_result.period
    row += 1
    ws[f'A{row}'] = 'Property:'
    ws[f'B{row}'] = engine_result.property_name
    row += 1
    ws[f'A{row}'] = 'Status:'
    ws[f'B{row}'] = engine_result.status
    row += 2

    # Summary statistics
    ws[f'A{row}'] = 'Summary Statistics'
    ws[f'A{row}'].font = Font(name='Calibri', size=12, bold=True)
    row += 1

    summary_metrics = [
        ('Files Processed', summary_data.get('files_processed', 0)),
        ('Parsers Succeeded', summary_data.get('parsers_succeeded', 0)),
        ('GL Accounts', summary_data.get('gl_accounts', 0)),
        ('GL Transactions', summary_data.get('gl_transactions', 0)),
        ('GL Balanced', summary_data.get('gl_balanced', False)),
        ('Invoice Matches', summary_data.get('invoice_matches', 0)),
        ('Bank Matches', summary_data.get('bank_matches', 0)),
        ('Budget Variances Flagged', summary_data.get('budget_variances_flagged', 0)),
    ]

    for label, value in summary_metrics:
        ws[f'A{row}'] = label
        ws[f'B{row}'] = value
        row += 1

    row += 1
    ws[f'A{row}'] = 'Exception Summary'
    ws[f'A{row}'].font = Font(name='Calibri', size=12, bold=True)
    row += 1

    exception_metrics = [
        ('Errors', engine_result.error_count),
        ('Warnings', engine_result.warning_count),
        ('Total Issues', len(engine_result.exceptions)),
    ]

    for label, value in exception_metrics:
        ws[f'A{row}'] = label
        ws[f'B{row}'] = value
        row += 1

    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 20


def _write_exceptions_tab(wb: Workbook, engine_result):
    """Write Exceptions tab with all flagged issues."""
    ws = wb.create_sheet('Exceptions')

    headers = ['Severity', 'Category', 'Source', 'Description', 'Resolved']
    for col_num, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_num, value=header)
        _apply_style(cell, _header_style())

    # Write exception rows
    for row_num, exc in enumerate(engine_result.exceptions, start=2):
        alternate = (row_num - 2) % 2 == 1
        style = _data_style(alternate)

        # Color code by severity
        if exc.severity == 'error':
            style['fill'] = PatternFill(start_color='FFC7CE', end_color='FFC7CE', fill_type='solid')
        elif exc.severity == 'warning':
            style['fill'] = PatternFill(start_color='FFEB9C', end_color='FFEB9C', fill_type='solid')

        ws.cell(row=row_num, column=1, value=exc.severity)
        _apply_style(ws.cell(row=row_num, column=1), style)

        ws.cell(row=row_num, column=2, value=exc.category)
        _apply_style(ws.cell(row=row_num, column=2), style)

        ws.cell(row=row_num, column=3, value=exc.source)
        _apply_style(ws.cell(row=row_num, column=3), style)

        ws.cell(row=row_num, column=4, value=exc.description)
        _apply_style(ws.cell(row=row_num, column=4), style)

        ws.cell(row=row_num, column=5, value='Yes' if exc.resolved else 'No')
        _apply_style(ws.cell(row=row_num, column=5), style)

    _auto_width_columns(ws, len(headers))


def _write_budget_variances_tab(wb: Workbook, engine_result):
    """Write Budget Variances tab."""
    ws = wb.create_sheet('Budget Variances')

    headers = ['Account Code', 'Account Name', 'PTD Actual', 'PTD Budget', 'Variance', 'Variance %']
    for col_num, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_num, value=header)
        _apply_style(cell, _header_style())

    # Write variance rows
    for row_num, var in enumerate(engine_result.budget_variances, start=2):
        alternate = (row_num - 2) % 2 == 1

        ws.cell(row=row_num, column=1, value=var.get('account_code', ''))
        _apply_style(ws.cell(row=row_num, column=1), _data_style(alternate))

        ws.cell(row=row_num, column=2, value=var.get('account_name', ''))
        _apply_style(ws.cell(row=row_num, column=2), _data_style(alternate))

        ws.cell(row=row_num, column=3, value=var.get('ptd_actual', 0))
        _apply_style(ws.cell(row=row_num, column=3), _currency_style(alternate))

        ws.cell(row=row_num, column=4, value=var.get('ptd_budget', 0))
        _apply_style(ws.cell(row=row_num, column=4), _currency_style(alternate))

        ws.cell(row=row_num, column=5, value=var.get('variance', 0))
        _apply_style(ws.cell(row=row_num, column=5), _currency_style(alternate))

        var_pct = var.get('variance_pct', 0)
        ws.cell(row=row_num, column=6, value=var_pct / 100 if var_pct else 0)
        _apply_style(ws.cell(row=row_num, column=6), _percent_style(alternate))

    if not engine_result.budget_variances:
        ws['A2'] = 'No material variances flagged'
        ws['A2'].font = Font(name='Calibri', size=11, italic=True)

    _auto_width_columns(ws, len(headers))


def _write_bank_recon_tab(wb: Workbook, engine_result):
    """Write Bank Reconciliation tab."""
    ws = wb.create_sheet('Bank Recon')

    headers = ['Source A', 'Source B', 'Key', 'Amount A', 'Amount B', 'Matched', 'Variance', 'Description']
    for col_num, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_num, value=header)
        _apply_style(cell, _header_style())

    # Write match rows
    for row_num, match in enumerate(engine_result.gl_bank_matches, start=2):
        alternate = (row_num - 2) % 2 == 1

        ws.cell(row=row_num, column=1, value=match.source_a)
        _apply_style(ws.cell(row=row_num, column=1), _data_style(alternate))

        ws.cell(row=row_num, column=2, value=match.source_b)
        _apply_style(ws.cell(row=row_num, column=2), _data_style(alternate))

        ws.cell(row=row_num, column=3, value=match.key)
        _apply_style(ws.cell(row=row_num, column=3), _data_style(alternate))

        ws.cell(row=row_num, column=4, value=match.amount_a)
        _apply_style(ws.cell(row=row_num, column=4), _currency_style(alternate))

        ws.cell(row=row_num, column=5, value=match.amount_b)
        _apply_style(ws.cell(row=row_num, column=5), _currency_style(alternate))

        ws.cell(row=row_num, column=6, value='Yes' if match.matched else 'No')
        _apply_style(ws.cell(row=row_num, column=6), _data_style(alternate))

        ws.cell(row=row_num, column=7, value=match.variance)
        _apply_style(ws.cell(row=row_num, column=7), _currency_style(alternate))

        ws.cell(row=row_num, column=8, value=match.description)
        _apply_style(ws.cell(row=row_num, column=8), _data_style(alternate))

    if not engine_result.gl_bank_matches:
        ws['A2'] = 'No bank reconciliation data available'
        ws['A2'].font = Font(name='Calibri', size=11, italic=True)

    _auto_width_columns(ws, len(headers))


def _write_debt_service_tab(wb: Workbook, engine_result):
    """Write Debt Service tab."""
    ws = wb.create_sheet('Debt Service')

    ds_check = engine_result.debt_service_check or {}

    # Title
    ws['A1'] = 'Debt Service Reconciliation'
    ws['A1'].font = Font(name='Calibri', size=12, bold=True)

    # Summary
    row = 3
    ws[f'A{row}'] = 'GL Interest Expense:'
    ws[f'B{row}'] = ds_check.get('gl_interest_expense', 0)
    ws[f'B{row}'].number_format = '$#,##0.00'
    row += 1
    ws[f'A{row}'] = 'Loan Interest Total (YTD):'
    ws[f'B{row}'] = ds_check.get('loan_interest_total', 0)
    ws[f'B{row}'].number_format = '$#,##0.00'
    row += 1
    ws[f'A{row}'] = 'Variance:'
    ws[f'B{row}'] = ds_check.get('variance', 0)
    ws[f'B{row}'].number_format = '$#,##0.00'
    row += 1
    ws[f'A{row}'] = 'Reconciled:'
    ws[f'B{row}'] = 'Yes' if ds_check.get('reconciled', False) else 'No'
    row += 2

    # Loan details
    ws[f'A{row}'] = 'Loan Details'
    ws[f'A{row}'].font = Font(name='Calibri', size=11, bold=True)
    row += 1

    loan_headers = ['Loan Name', 'Principal Balance', 'Interest Paid YTD']
    for col_num, header in enumerate(loan_headers, start=1):
        cell = ws.cell(row=row, column=col_num, value=header)
        _apply_style(cell, _header_style())
    row += 1

    for loan in ds_check.get('loans', []):
        ws[f'A{row}'] = loan.get('name', '')
        ws[f'B{row}'] = loan.get('principal_balance', 0)
        ws[f'B{row}'].number_format = '$#,##0.00'
        ws[f'C{row}'] = loan.get('interest_paid_ytd', 0)
        ws[f'C{row}'].number_format = '$#,##0.00'
        row += 1

    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 20
    ws.column_dimensions['C'].width = 20


# ── Test/Demo ────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Simple test: create a minimal EngineResult and generate a report.
    """
    from engine import EngineResult, Exception_
    from datetime import datetime

    # Create a minimal engine result
    result = EngineResult(
        run_id="TEST_20260403_120000",
        run_at=datetime.now().isoformat(),
        period="Mar-2026",
        property_name="Test Property",
    )

    # Add some test exceptions
    result.add_exception(
        "error", "balance", "gl_validation",
        "GL is not balanced",
        total_debits=100000.00,
        total_credits=99999.50,
    )
    result.add_exception(
        "warning", "variance", "budget_comparison",
        "Material variance in account 401000",
        variance=5000.00,
        variance_pct=15.5,
    )

    # Add test budget variances
    result.budget_variances = [
        {
            'account_code': '401000',
            'account_name': 'Rental Income',
            'ptd_actual': 50000.00,
            'ptd_budget': 45000.00,
            'variance': 5000.00,
            'variance_pct': 11.1,
        }
    ]

    # Add test GL bank matches
    from engine import MatchResult
    result.gl_bank_matches = [
        MatchResult(
            source_a="GL",
            source_b="Bank",
            key="Ending Balance",
            amount_a=250000.00,
            amount_b=249500.00,
            matched=False,
            variance=500.00,
            description="GL Cash vs Bank Balance",
        )
    ]

    # Set summary
    result.summary = {
        'files_processed': 5,
        'parsers_succeeded': 5,
        'gl_accounts': 75,
        'gl_transactions': 500,
        'gl_balanced': False,
        'invoice_matches': 45,
        'bank_matches': 10,
        'budget_variances_flagged': 3,
        'exceptions_error': 1,
        'exceptions_warning': 5,
        'status': 'WARNINGS',
    }

    # Generate reports
    output_dir = '/tmp'
    main_report_path = generate_report(result, f'{output_dir}/test_main_report.xlsx')
    exception_report_path = generate_exception_report(result, f'{output_dir}/test_exception_report.xlsx')

    print(f"Main report generated: {main_report_path}")
    print(f"Exception report generated: {exception_report_path}")
